apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
    tier: backend
spec:
  selector:
    app: redis
    tier: backend
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
